### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by bfontaine** [swissup/module-font-awesome-5#1]
Hello, what is the license for the code here? Could you add a `LICENSE` file?
Thanks!

**Comment by vovayatsyuk** [comment]
I'm not sure which license to add. 

Our code [is MIT licensed](https://github.com/swissup/module-font-awesome-5/blob/master/composer.json#L13), while font awesome bundled in this module uses its own [Font Awesome Free License](https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt).

Do you know what to do in such cases?

**Comment by bfontaine** [comment]
Ah, thank you I didn’t think of looking in `composer.json`!

I’m not familiar with such cases, I guess having a file that explains which part of the repo is under which licence works, since that’s what Font Awesome does.
