### ISSUE TITLE
Update to the latest font awesome version?

### ISSUE THREAD

**Issue by kunzi** [swissup/module-font-awesome-5#2]
Would it be possible to get an update to the latest version of the Font awesome?

**Comment by vovayatsyuk** [comment]
Hi! The latest font awesome is 6.x and we are not going to update or create a new package for it. If you are interested in 5.x - yes I will update the repo.

**Comment by vovayatsyuk** [comment]
Done. https://github.com/swissup/module-font-awesome-5/commit/356e77a1e9bb5a99173b7783a6d5c0631dddfea1
